[package]
name = "data-analysis-app"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.1"
dotenvy = "0.15.7"
llm-chain = "0.13.0"
llm-chain-openai = "0.13.0"
tokio = { version = "1.25.0", features = ["macros", "rt-multi-thread"] }
